### ISSUE TITLE
Packet encoding

### ISSUE THREAD

**Issue by coldchip** [GrowtopiaNoobs/GrowtopiaServer#3]
Hey, I decided to write a much cleaner version of your code in PHP using PHP sockets.

The first problem i stuck with is the packets are being obfuscated/encoded/encrypted ?!

I ran Wireshark and the first packet it sent to GT servers was `cfff7eb6581974ef837b88b1fdf1df576b999b36fcbb243e8a642656d33bdd8b4ed917a48385`

Can you explain to me what the Growtopia packets are encoded in? 

I have trouble decoding the packet :( 

also, i have no knowledge of C++/C and can't run your code because i'm using ubuntu. 

And thanks very much if you can help me with this :)

**Comment by GrowtopiaNoobs** [comment]
This code use library called ENet http://enet.bespin.org/ and it uses range encoder and crc checksums. So you first would need to rewrite ENet also I am not sure if PHP sockets would work, because I think that ENet should be based on raw UDP layer.

**Comment by coldchip** [comment]
Hey! Thanks for your reply. I will look into range encoding and hopefully write a ENET library in PHP!

**Comment by ReimarPB** [comment]
Any updates on this? I'm having exactly the same problem and I can't seem to find much information about enet/range encoding etc. anywhere. While most packets are complete gibberish, I can still sometimess see things like action|drop or action|quit in the middle of it all so I assume not all of it is encoded?

**Comment by DEERUX** [comment]
Why would you require this? The ENet server/client does this by default, is your purpose to rewrite the library or some parts of it or what then??

**Comment by ReimarPB** [comment]
I actually wanted to make this in node.js but haven't been able to get [the enet module](https://www.npmjs.com/package/enet) to work for some reason. I also recently found [this wrapper](https://github.com/Memeo/enet-js) but it requires node-waf to install, which from my research does not exist for Windows.

**Comment by ReimarPB** [comment]
Turns out both of these modules are really outdated and not maintained, this is probably why I couldn't get one of them to work. I can get regular UDP protocols to work though, the data is just unreadable. Any chance it would be possible to recreate enet's encoding in JavaScript?

There is little information about range encoding on the internet and the few pieces of code I found that should implement range encoding were not able to decode Growtopia's packets.

I really have no idea of what to do here and I still don't understand how range encoding actually works. If I want to create a Growtopia server, will I have to learn C++ then?

**Comment by DrOreo002** [comment]
Not really, I've implemented enet at Java usin JNI. Performance is great it only consumes less than 100 mb of memory. I also had protocol library for Growtopia written in java, with that you can make a bot in less than 10 minutes. Check my pinned repo

**Comment by coldchip** [comment]
@ReimarPB 

 I had tried it but to no avail, even gone as far to compile the ENet C code into JavaScript ASM(Emscripten Compiller), nah no luck because of how NodeJS Raw Sockets works. I also don't recommend using JavaScript because how Threads work on this language and also it will be slower than a normal C/C++ program.

If you want to really do it then you should make a ENet repeater in C and send the events into NodeJS using Linux pipes or TCP or something, i did that with PHP last time..... Doesn't turn out great.

**Comment by ReimarPB** [comment]
@DrOreo002 I have tried your Enet Java library but I can't get it to work. When running `build-windows.bat` I get the following output:

```
ENetJavaLib.c: In function 'Java_enetjava_ENetLib_set_1application_1data':
ENetJavaLib.c:108:14: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
   peer->data = nativeString;
              ^
[BUILD] .o File has been generated. Now generating .so file
callbacks.o: file not recognized: file format not recognized
collect2.exe: error: ld returned 1 exit status
[BUILD] .dll File has been generated. Build success
```

Also, I can't see the output when running `build-windows.sh` because it closes immediatedly but I'm assuming it's the same because it does not generate a dll file.

I have also just tried the ENetJavaLib.dll that comes with your repo and when using that, the program doesn't recognize when I try to connect to the server.

**Comment by DrOreo002** [comment]
I also had that error when trying to compile, it was something caused by the build tools itself (mingw), I apparently installed mingw version 32 bit where enet is actually 64 bit. I'll add that problem into common problem section later

**Comment by ReimarPB** [comment]
Where do I install the 64-bit version? [the download page](https://osdn.net/projects/mingw/releases/) says that they only offer a 32-bit version.

Also, while we're at it, you forgot to add some getNativeState() methods in some of your ENetJava files but that was an easy fix.

**Comment by DrOreo002** [comment]
> Where do I install the 64-bit version? [the download page](https://osdn.net/projects/mingw/releases/) says that they only offer a 32-bit version.
> 
> Also, while we're at it, you forgot to add some getNativeState() methods in some of your ENetJava files but that was an easy fix.

Well If you taken a look into the source yeah it will not be there because I'm using lombok, not sure tho I forgot the download links xD

**Comment by ReimarPB** [comment]
I did install lombok too but I might've installed it wrong, idk because I'm very inexperienced with Java.

**Comment by ReimarPB** [comment]
Soo where do I download a 64-bit version of mingw?

**Comment by ReimarPB** [comment]
I now tried installing it using [this tutorial](https://www.youtube.com/watch?v=aXF4A5UeSeM) but I get the same output and it still does not work. Could you please tell me where I can get a 64-bit version of MinGW??
